# This is a basic workflow to help you get started with Actions

name: Code review using Rails Best Practices
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the project_revision branch
  push:
    branches: [ project_revision ]
  pull_request:
    branches: [ project_revision ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rails_best_practices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using Rails Best Practices
        uses: moneyforward/rails_best_practices-action@v0
